### ISSUE TITLE
Two ports being passed to ssh

### ISSUE THREAD

**Issue by nf9k** [flyingrhinonz/nccm#18] opened 2022-09-12 22:05 UTC
When I try to connect to an entry that has a custom port defined, both 22 and my custom port (1234) are sent:

nccm: About to ssh using:
ssh xxxx@xxx-xxx-xxxx.domain.net -p 22 -o ServerAliveInterval=30 -p 1234

Using the same machine and same nccm.yml, I see the issue with 1.6.28, but not with 1.5.2.

I did run my nccm.yml through a validator.

Let me know what else you'd like.

**Comment by flyingrhinonz** [comment] 2022-09-14 02:06
Hmm, haven't noticed that before.
Let me check it on the weekend.

**Comment by flyingrhinonz** [comment] 2022-09-14 22:35
Sorry , works for me.

Can you please do this:
create a new copy of your nccm.yml file ONLY WITH the following:
- all the nccm controls setup (this is important so send it as is, but feel free to fake stuff like paths if you wish)
- only one block of config corresponding to one connection

Test out this new config in your own place to verify the problem still happens.

Replace your real user and server with fake data - but ensure that you use exactly the same format (ip or hostname, same structure, etc).
I need all the nccm controls setup (this is important so send it as is, but feel free to fake stuff like paths if you wish, just keep the same formatting and structure).
gzip this yaml file to prevent email from breaking the formatting.
Then send the gzip file to my email which is at the top of the nccm page.
Also email me the connection establishment text you get from the output (fake the private stuff too).

Thanks,

**Comment by flyingrhinonz** [comment] 2022-10-08 21:03
Has anyone else encountered this bug?
Please let me know so I can fix it, or I'll close this ticket in a couple weeks.

**Comment by nf9k** [comment] 2022-10-09 00:42
I'm back from vacation.  Let me confirm via your tests and I'll advise.  Thanks.

**Comment by flyingrhinonz** [comment] 2022-11-10 22:10
Closing ticket until it can be confirmed.

**Closed as completed by flyingrhinonz** 2022-11-10 22:10 UTC
